Repository senaite/senaite.health, pull requests merged in 2018-02, with the labels that each got.

#45 ConfigurationConflictError in "The workflow actions menu"
  CHANGES.rst
  bika/health/browser/overrides.zcml
Labels: bug, priority: high

#49 Default publication preference for Patients in Clients vocabulary error
  CHANGES.rst
  bika/health/content/client.py
Labels: bug, priority: medium

#50 Date Collected missing in reports
  bika/health/browser/analysisrequest/templates/reports/default.pt
Labels: bug

#52 Date Reported missing in reports
  bika/health/browser/analysisrequest/templates/reports/default.pt
Labels: bug

#53 Redirect to Patient's ARs view when accessing a Patient
  bika/health/browser/patients/folder_view.py
Labels: change, priority: low
