Repository senaite/senaite.health, pull requests merged in 2018-04, with the labels that each got.

#63 Show doctor in Analysis Requests listings
  CHANGES.rst
  bika/health/browser/analysisrequests/view.py
Labels: addition

#64 Samples list not filtered in Doctor Samples view
  CHANGES.rst
  bika/health/browser/doctor/samples.py
Labels: bug

#65 Fix api import
  bika/health/validators.py
Labels: bug

#69 Make License visible in repository overview
  CHANGES.rst
  LICENSE.rst
Labels: addition

#70 Index and Metadata optimizations for AR Listing View
  CHANGES.rst
  bika/health/__init__.py
  bika/health/browser/analysisrequests/view.py
  bika/health/catalog/analysisrequest_catalog.py
  bika/health/catalog/indexers/__init__.py
  bika/health/catalog/indexers/analysisrequest.py
  bika/health/catalog/indexers/configure.zcml
  bika/health/configure.zcml
  bika/health/content/analysisrequest.py
  bika/health/content/configure.zcml
  bika/health/upgrade/v01_01_002.py
  bika/health/utils/__init__.py
Labels: addition, priority: high

#71 Slow Reference Widgets in 'Add Case' View
  CHANGES.rst
  bika/health/content/batch.py
Labels: bug, priority: high
