Repository senaite/senaite.health, pull requests merged in 2018-03, with the labels that each got.

#48 Redirect to Patient's ARs view after Patient creation
  CHANGES.rst
  bika/health/skins/bika_health/validate_integrity.cpy
Labels: change, priority: low

#57 Correct CHANGES.rst formatting
  CHANGES.rst
Labels: change, priority: low

#56 Add option and validator to make Client Patient ID unique
  CHANGES.rst
  bika/health/catalog/patient_catalog.py
  bika/health/content/bikasetup.py
  bika/health/content/patient.py
  bika/health/upgrade/v01_01_001.py
  bika/health/validators.py
Labels: addition

#61 Fix unique Client Patient ID validation
  bika/health/validators.py
Labels: bug, priority: high

#62 Apply PEP8 style guidelines to patient.py
  bika/health/content/patient.py
Labels: change

#44 Traceback on "copy to new" Analysis Request
  CHANGES.rst
  bika/health/content/analysisrequest.py
Labels: bug, priority: high
