Repository senaite/senaite.health, pull requests merged in 2018-05, with the labels that each got.

#77 Remove Dry Matter references
  CHANGES.rst
  bika/health/browser/analysisrequest/templates/ar_add_health_standard.pt
  bika/health/browser/analysisrequest/templates/reports/default.pt
Labels: addition

#75 Patient & Doctor URL values in AR Listing Catalog contain 'host' info.
  CHANGES.rst
  bika/health/catalog/indexers/analysisrequest.py
  bika/health/upgrade/v01_01_002.py
Labels: bug, priority: high

#67 Test machinery
  .travis.yml
  bika/health/testing.py
  bika/health/tests/base.py
  bika/health/tests/doctests/Patients.rst
  bika/health/tests/halt/test_doctests.py
  bika/health/tests/test_regulatoryinspector.robot
  bika/health/tests/test_robot.py
  bika/health/tests/test_textual_doctests.py
  bootstrap.py
  buildout.cfg
  setup.py
  templates/write_contributors.py.in
  travis.cfg
Labels: addition

#78 Include Travis badge in README
  README.rst
Labels: addition

#80 Remove dependency to senaite.core's MultiFileView
  bika/health/browser/patient/files.py
Labels: bug
