Repository senaite/senaite.health, pull requests merged in 2018-08, with the labels that each got.

#97 Traceback accessing Doctor samples when user is not Manager, LabManager or LabClerk
  CHANGES.rst
  bika/health/browser/samples/folder_view.py
Labels: bug

#99 Traceback when publishing health results from inside a client
  CHANGES.rst
  bika/health/browser/client/overrides.zcml
Labels: bug

#86 Allow client contacts to list/add/edit Clinical Cases from their own Client
  CHANGES.rst
  bika/health/ajax/client.py
  bika/health/ajax/configure.zcml
  bika/health/setuphandlers.py
  bika/health/static/js/bika.health.batch.js
  bika/health/upgrade/v01_01_003.py
Labels: addition

#101 Add button was not displayed in Client's Cases view
  bika/health/browser/client/batches.py
Labels: P1: Urgent, bug

#103 All Samples are listed inside Case context
  CHANGES.rst
  bika/health/browser/batch/samples.py
Labels: P0: Critical, bug

#102 Doctors assigned to other clients are listed when logged as Client
  CHANGES.rst
  bika/health/browser/doctors/folder_view.py
  bika/health/browser/doctors/getdoctors.py
  bika/health/static/js/bika.health.analysisrequest.add.js
  bika/health/static/js/bika.health.batch.js
Labels: Dependencies, P0: Critical, bug
