Repository senaite/senaite.health, pull requests merged in 2019-10, with the labels that each got.

#141 Unable to Deactivate Doctors
  CHANGES.rst
  bika/health/profiles/default/workflows/senaite_health_doctor_workflow/definition.xml
  bika/health/upgrade/v01_02_002.py
Labels: 1.3, P2: Very Important, bug

#143 Avoid attribute error on Patient creation
  bika/health/validators.py
Labels: bug

#146 Move skin layer after the custom layer
  CHANGES.rst
  bika/health/profiles/default/skins.xml
  bika/health/setuphandlers.py
Labels: bug

#147 Reindex content structure after install to fix missing icons
  CHANGES.rst
  bika/health/setuphandlers.py
Labels: P4: Nice To Have, bug

#145 Fix Error trying to edit analysis specifications
  CHANGES.rst
  bika/health/configure.zcml
  bika/health/widgets/analysisspecificationwidget.py
  bika/health/widgets/configure.zcml
Labels: P2: Very Important, bug

#142 Fix Client contacts cannot add cases
  bika/health/adapters/addsample.py
  bika/health/adapters/configure.zcml
  bika/health/adapters/widgetvisibility.py
  bika/health/browser/batchfolder.py
  bika/health/content/batch.py
Labels: 1.3, P4: Nice To Have, bug

#148 Delete overridden indexes for batches
  CHANGES.rst
  bika/health/browser/batch/getbatchinfo.py
  bika/health/content/batch.py
  bika/health/content/client.py
  bika/health/content/configure.zcml
Labels: 1.3, bug

#149 Remove Add Sample view js and use field adapters instead
  bika/health/adapters/addsample.py
  bika/health/adapters/configure.zcml
  bika/health/profiles/default/jsregistry.xml
  bika/health/static/js/bika.health.analysisrequest.add.js
  bika/health/static/js/bika.health.loader.js
  bika/health/upgrade/v01_02_002.py
Labels: Dependencies, Enhancement

#151 Additional buttons in Batch and Patient add/edit views
  CHANGES.rst
  bika/health/setuphandlers.py
  bika/health/skins/bika_health/batch_edit.pt
  bika/health/skins/bika_health/patient_edit.pt
  bika/health/skins/bika_health/validate_integrity.cpy
  bika/health/subscribers/batch.py
  bika/health/subscribers/configure.zcml
  bika/health/upgrade/v01_02_000.py
  bika/health/upgrade/v01_02_001.py
  bika/health/utils.py
Labels: addition
