Repository senaite/senaite.health, pull requests merged in 2019-08, with the labels that each got.

#130 Unable to Deactivate Doctors
  .travis.yml
  bika/health/permissions.py
  bika/health/permissions.zcml
  bika/health/profiles/default/rolemap.xml
  bika/health/profiles/default/workflows/senaite_health_doctor_workflow/definition.xml
  bika/health/upgrade/v01_02_002.py
Labels: 1.3, bug

#131 Autofill ClientPatientID field in Sample Add form when Patient defined
  CHANGES.rst
  bika/health/adapters/addsample.py
  bika/health/adapters/configure.zcml
  bika/health/static/js/bika.health.analysisrequest.add.js
Labels: P1: Urgent, bug

#132 Autofill Case in Sample Add form when Batch defined in request
  CHANGES.rst
  bika/health/adapters/addsample.py
  bika/health/adapters/configure.zcml
Labels: Enhancement, P1: Urgent

#133 System clearing patient first name on editing patient
  CHANGES.rst
  bika/health/static/js/bika.health.patient.js
Labels: P1: Urgent, bug

#134 ReferenceWidget for client searches in Add Patient form
  CHANGES.rst
  bika/health/content/patient.py
Labels: Enhancement
